Hello world.txt
created hello world text file
- a
- b
- c
=> Create Hello world.txt

Hello world.txt
Deep unknown lore just dropped
=> doc(new lore): added goodbye world

MonstieWash/Assets/Scripts.meta, MonstieWash/Assets/Scripts/TutorialFeature.cs, MonstieWash/Assets/Scripts/TutorialFeature.cs.meta
This feature adds the capability to display secret numbers and messages.
=> 003 tutorial feature

MonstieWash/Assets/Prefabs/BrushTool.prefab, MonstieWash/Assets/Prefabs/Dirt.prefab, MonstieWash/Assets/Prefabs/Dirt.prefab.meta, MonstieWash/Assets/Prefabs/GameManager.prefab, MonstieWash/Assets/Prefabs/GameManager.prefab.meta, MonstieWash/Assets/Prefabs/PlayerHand.prefab, MonstieWash/Assets/Scenes/MonstieWash.unity, MonstieWash/Assets/Scenes/NavTests/Init.unity, MonstieWash/Assets/Scenes/NavTests/NavTest.unity, MonstieWash/Assets/Scenes/NavTests/NavTest2.unity, MonstieWash/Assets/Scenes/NavTests/NavTest3.unity, MonstieWash/Assets/Scripts/Controls/PlayerInput.cs, MonstieWash/Assets/Scripts/Controls/PlayerInput.inputactions, MonstieWash/Assets/Scripts/DragTool.cs, MonstieWash/Assets/Scripts/Eraser.cs, MonstieWash/Assets/Scripts/InputManager.cs, MonstieWash/Assets/Scripts/InputManager.cs.meta, MonstieWash/Assets/Scripts/PlayerHand.cs, MonstieWash/Assets/Scripts/PlayerHandInput.cs.meta, MonstieWash/Assets/Scripts/RoomSaver.cs, MonstieWash/Assets/Scripts/Tool.cs, MonstieWash/Assets/Scripts/TraversalObject.cs, MonstieWash/Assets/Tools/Soap.asset, MonstieWash/ProjectSettings/TagManager.asset
Reworked how the input system was implemented and updated the existing features to work with the new input system. Also did some small cleanup during this process.
📝 Checklist before requesting a review:
=> 161 input system implementation

MonstieWash/Assets/Prefabs/Erasables/Dirt.prefab, MonstieWash/Assets/Prefabs/Erasables/Dirt2.prefab, MonstieWash/Assets/Prefabs/Erasables/Dirt_Clump.prefab, MonstieWash/Assets/Prefabs/Erasables/Mold.prefab, MonstieWash/Assets/Prefabs/Interactable/PlayerHand.prefab, MonstieWash/Assets/Prefabs/Tools/Brush.prefab, MonstieWash/Assets/Prefabs/Tools/Floss.prefab, MonstieWash/Assets/Prefabs/Tools/Sponge.prefab, MonstieWash/Assets/Prefabs/Tools/Wipe.prefab, MonstieWash/Assets/Prefabs/UI/CBCanvas.prefab, MonstieWash/Assets/Scenes/Game Scenes/SlimeLevel/SlimeStartingScene.unity, MonstieWash/Assets/Scripts/UIManager.cs, MonstieWash/ProjectSettings/TagManager.asset
- Made 2 sorting layers - DirtFront and DirtBack
- put prefabs into correct sorting layers
Mimic level works as intended, slime lvl is broken bc of clipboard changes. I did not touch the levels bc i think its more appropriate to update them in feature branches relevant to them
=> 270 fix tool layering

MonstieWash/Assets/Animation/Mimic/Front/Mimic_Front.controller, MonstieWash/Assets/Scripts/MonsterAi/SlimeMoods/slimeAngry.asset, MonstieWash/Assets/Tools/Brush.asset
- mimic animations now work 
- edits to slime angry so its not constantly angry
- made brush stronger bc it was super slow in the lecture
=> Patches for w11 demo

MonstieWash/Assets/Scenes/Testing/Testing Scenes/197-EraserTesting.unity, MonstieWash/Assets/Scenes/Testing/Testing Scenes/197-EraserTesting.unity.meta, MonstieWash/Assets/Scripts/Erasing/Eraser.cs, MonstieWash/Assets/Scripts/Erasing/Tool.cs
Just a lil ol' feature reworking the erasing algorithm to work for all transformations of erasables. Give it a test drive in any local scene near you!
📝 Checklist before requesting a review:
=> 197 dirt transformation

MonstieWash/Assets/Prefabs/Background Room.prefab, MonstieWash/Assets/Prefabs/Background Room.prefab.meta, MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicBack.unity, MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicFront.unity, MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicLeft.unity, MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicRight.unity
Created a prefab for the background image and added it to the various views of the mimic. Unsure where to place it in the prefab folders though.
=> 304 background prefab

MonstieWash/Assets/Prefabs/Management/Managers/UpgradeMananger.prefab, MonstieWash/Assets/Scripts/Upgrades/ToolUpgrade.cs, MonstieWash/Assets/Scripts/Upgrades/UpgradeManager.cs
Small changes to add sound player to upgrade scene and play sound on upgrade
📝 Checklist before requesting a review:
[x] I have run this branch locally
[x] I have performed a self-review of my code
[x] I have confirmed critical features still function
=> 379-sting-sound-functionality

MonstieWash/Assets/Animation/Hand/hd_idle_ani.anim, MonstieWash/Assets/Animation/Hand/hd_idle_ani.anim.meta
=> hand idle ani

MonstieWash/Assets/Prefabs/UI/ClientUITemplate.prefab, MonstieWash/Assets/Scenes/Game Scenes/Menus/LevelSelectScene.unity
updated level select menu with new dialogue made by joel (this was done a while ago but forgot to be implemented oops)
=> 140 select menu dialogue

MonstieWash/Assets/Scripts/Traversal/GameSceneManager.cs, MonstieWash/Assets/Sprites/Monsters/Mimic/IsolatedPupil.png.meta
=> fix(polaroids): I used my braincell. It now works. However, my confidence is shattered.

MonstieWash/Assets/Animation/Monsters/Slime/Combined/Attack/Slime@atk_ex.anim, MonstieWash/Assets/Scenes/Game Scenes/Slime/SlimeFront.unity
Added water spray vfx to slime's attack animation. Please do a quick check to see if its done correctly (first time messing with our animation system)
=> 452 slime attack vfx

MonstieWash/Assets/Materials.meta, MonstieWash/Assets/Materials/TaskItem.mat, MonstieWash/Assets/Materials/TaskItem.mat.meta, MonstieWash/Assets/Prefabs/Erasables/Dirt.prefab, MonstieWash/Assets/Prefabs/Erasables/Dirt2.prefab, MonstieWash/Assets/Prefabs/Erasables/Dirt_Clump.prefab, MonstieWash/Assets/Prefabs/Erasables/Mold.prefab, MonstieWash/Assets/Prefabs/Hand/PlayerHand.prefab, MonstieWash/Assets/Prefabs/Interactable/Item.prefab, MonstieWash/Assets/Scenes/Testing/Testing Scenes/460-Scanner.unity, MonstieWash/Assets/Scenes/Testing/Testing Scenes/460-Scanner.unity.meta, MonstieWash/Assets/Scripts/Controls/InputManager.cs, MonstieWash/Assets/Scripts/Controls/PlayerInput.cs, MonstieWash/Assets/Scripts/Controls/PlayerInput.inputactions, MonstieWash/Assets/Scripts/Items/StuckItem.cs, MonstieWash/Assets/Scripts/Player/Scanner.cs, MonstieWash/Assets/Scripts/Player/Scanner.cs.meta, MonstieWash/Assets/Shaders.meta, MonstieWash/Assets/Shaders/Sprites-ColourLerp.shader, MonstieWash/Assets/Shaders/Sprites-ColourLerp.shader.meta
You can now scan for incomplete tasks! The scanning can be tweaked via the scanner script and the sprite's colours.
📝 Checklist before requesting a review:
=> 460 task scanner

MonstieWash/Assets/Scripts/Items/ItemPickup.cs
Bones now hold to remove, drop when done.
=> 459 bone controls

MonstieWash/Assets/Scenes/Game Scenes/Menus/GameStartingScene.unity
=> 468 starting controller prompt

MonstieWash/Assets/Scenes/Game Scenes/Bedroom/LevelSelectScene.unity, MonstieWash/Assets/Scenes/Game Scenes/Bedroom/UpgradeScene.unity, MonstieWash/Assets/Scenes/Game Scenes/Menus/ScoreSummary.unity, MonstieWash/Assets/Scripts/Player/PlayerHealth.cs, MonstieWash/Assets/Scripts/Traversal/GameSceneManager.cs, MonstieWash/Assets/Scripts/Traversal/TraversalMenu.cs
Removed death destroyer of worlds, immortality has been enacted.
=> 504 remove death

MonstieWash/Assets/ScriptableObjects/MonsterMoods/Slime/slimeAngry.asset, MonstieWash/Assets/ScriptableObjects/MonsterMoods/Slime/slimeHappy.asset, MonstieWash/Assets/ScriptableObjects/MonsterMoods/Slime/slimeSad.asset
=> 510 slime moods

MonstieWash/Assets/Scripts/Controls/PlayerInput.cs, MonstieWash/Assets/Scripts/Controls/PlayerInput.inputactions
X button now swaps tools on controller
Right click starts the scan for dirt. That's basically it
=> feat(changed controls): remapped both controller and K&M

MonstieWash/Assets/Scenes/Game Scenes/Slime/SlimeStartingScene.unity, MonstieWash/Assets/ScriptableObjects/MonsterMoods/Slime/slimeAngry.asset, MonstieWash/Assets/ScriptableObjects/MonsterMoods/Slime/slimeHappy.asset, MonstieWash/Assets/ScriptableObjects/MonsterMoods/Slime/slimeSad.asset
tried to make it so its mood doesn't change on its own (aside from the idle and anger moods), tried to implement the slime not staying angry so it only attacks maybe once or not at all per time it gets angry, and tried to make it start a little sad and get happy at end but i think the idle is a little stronger than the sad so players don't really see it start sad
=> 514 update-slime-ai

MonstieWash/Assets/Prefabs/UI/ToolUpgrade.prefab, MonstieWash/Assets/Scenes/Game Scenes/Bedroom/LevelSelectScene.unity, MonstieWash/Assets/Scenes/Game Scenes/Bedroom/UpgradeScene.unity, MonstieWash/Assets/Scenes/Game Scenes/Menus/ScoreSummary.unity
=> fix(Button Visibility): Buttons are now visible.

MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicBack.unity, MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicFront.unity, MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicLeft.unity, MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicRight.unity
Added parallax to bg for mimic level scenes (except mouth)
=> 574 mimic level parallax

MonstieWash/Assets/ScriptableObjects/SoundObjs/Sound Effects/BonePop.asset, MonstieWash/Assets/ScriptableObjects/SoundObjs/Sound Effects/BrushSound.asset, MonstieWash/Assets/ScriptableObjects/SoundObjs/Sound Effects/CompletionTwinkle.asset, MonstieWash/Assets/ScriptableObjects/SoundObjs/Sound Effects/Sparkle.asset
lowered the sound of brushing, as well as the bone, completion jingle and sparkle sounds
(it also says I changed the brush sound to play on awake even though its not ticked in unity (just like the others) and they all have 0 showing in github, not too sure what happened there)
=> 586-lowering brush sound effects

MonstieWash/Assets/Prefabs/MoodAffectors/CircleMoodArea.prefab, MonstieWash/Assets/Scenes/Game Scenes/Slime/SlimeBack.unity, MonstieWash/Assets/Scenes/Game Scenes/Slime/SlimeFront.unity, MonstieWash/Assets/Scripts/MonsterAi/MoodArea.cs, MonstieWash/Assets/Scripts/Player/PlayerHandAnimationController.cs
Pat your lil friends on the head or wherever they like and watch your hand go pat! All moodAreas use the `causesFlinch` field to selectively trigger the petting animation whenever they don't cause a flinch. ezpz lemon squeezy
=> 251 petting

MonstieWash/Assets/Animation/Monsters/Mimic/Emotion_ani/Mimic Full Ani/Mimic full animation.controller, MonstieWash/Assets/Animation/Monsters/Mimic/Emotion_ani/Mimic Full Ani/Mimic@ang_baseAlt.anim, MonstieWash/Assets/Animation/Monsters/Mimic/Emotion_ani/Mimic Full Ani/Mimic@ang_baseAlt.anim.meta, MonstieWash/Assets/Animation/Monsters/Mimic/Emotion_ani/Mimic Full Ani/Mimic@ang_ext.anim, MonstieWash/Assets/Animation/Monsters/Mimic/Emotion_ani/Mimic Full Ani/Mimic@hap_ext.anim, MonstieWash/Assets/Animation/Monsters/Mimic/Emotion_ani/Mimic Full Ani/Mimic@idle_base.anim, MonstieWash/Assets/Prefabs/Monsters/Mimic/Mimic_Front.prefab, MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicFront.unity
Mimic mood animations (front) implemented. Angry base animation is actually just transform being applied to a static sprite, which allows the dirt to track movement
=> 425 mimic mood anim

MonstieWash/Assets/Scripts/Erasing/ToolFX.cs
pls be kind i spent a long time on that one line pls it's my life's work 🙏
=> fix(tool pe bug): tool fx now stop when switching tools

MonstieWash/Assets/Prefabs/Hand/PlayerHand.prefab, MonstieWash/Assets/Prefabs/Monsters/Slime/Slime_body&eyes.prefab
Literally just added a rigidbody2d to the attack hitbox lol
=> fix(attack bug): attacks now register on stationary hand

MonstieWash/Assets/Scenes/Game Scenes/Slime/SlimeStartingScene.unity, MonstieWash/Assets/Scripts/UI/UIManager.cs
clipboard will automatically hide itself after a set time delay.
=> feat(clip autohide): clipboard hides itself after the set time

MonstieWash/Assets/Scripts/UI/UIManager.cs
=> fix(duplicate line items): it's fixed

MonstieWash/Assets/Scripts/Controls/InputManager.cs, MonstieWash/Assets/Scripts/Controls/PlayerInput.cs, MonstieWash/Assets/Scripts/Controls/PlayerInput.inputactions, MonstieWash/Assets/Scripts/Erasing/ToolFX.cs, MonstieWash/Assets/Scripts/Misc/DebugManager.cs, MonstieWash/Assets/Scripts/Tasks/TaskTracker.cs
fixed bug that caused the game to lock up when finishing a level. Also added a debug input on '=' to immediately finish a level.
=> 625 lock up bug

MonstieWash/Assets/Scenes/Game Scenes/Mimic/MimicStartingScene.unity, MonstieWash/Assets/Scenes/Game Scenes/Slime/SlimeStartingScene.unity, MonstieWash/Assets/Scripts/MonsterAi/MonsterBrain.cs, MonstieWash/Assets/Scripts/Tasks/TaskTracker.cs, MonstieWash/Assets/Scripts/UI/UIManager.cs
My greatest contribution to this project is removing the work I did for this project.
=> fix(removed clipboard): it's gone! where'd it go?

MonstieWash/Assets/Scenes/Game Scenes/Slime/SlimeBack.unity
Fixed slime attack triggering on slime back
=> 631 slime back bug

MonstieWash/Assets/Scenes/Game Scenes/Bedroom/LevelSelectScene.unity, MonstieWash/Assets/Scenes/Game Scenes/Menus/GameStartingScene.unity, MonstieWash/Assets/Scripts/Audio/SoundPlayer.cs, MonstieWash/Assets/Scripts/Traversal/GameSceneManager.cs, MonstieWash/Assets/Scripts/UI/MainMenu.cs, MonstieWash/Assets/Scripts/Video/VideoController.cs
-Main title video can hide list of chosen objects. 
-Main title video pauses music during playtime.
-Main title immediately leads into animatic and then slime level. 
-Slime taskboard now just starts level without animatic.
=> Feat: Requested changes.

MonstieWash/Assets/Scenes/Game Scenes/Menus/GameStartingScene.unity, MonstieWash/Assets/Scripts/Controls/InputManager.cs, MonstieWash/Assets/Scripts/Controls/PlayerInput.cs, MonstieWash/Assets/Scripts/Controls/PlayerInput.inputactions, MonstieWash/Assets/Scripts/Misc/DebugManager.cs, MonstieWash/Assets/Scripts/Misc/GalleryManager.cs, MonstieWash/Assets/Scripts/Traversal/FinishLevelButton.cs, MonstieWash/Assets/Scripts/Traversal/GameSceneManager.cs, MonstieWash/Assets/Scripts/Video/VideoController.cs
Just a couple fixes and updates from designer feedback.
- Afk time on main menu before animatic starts increased to 10
- Debug controls allow for skipping animatic
- Debug controls now require combinations to be held to execute
- Fixed gallery positional data reading
=> Polish and fixes

MonstieWash/Assets/Prefabs/UI/Tutorial/TutorialManager.prefab, MonstieWash/Assets/Scenes/Game Scenes/Slime/SlimeDecorate.unity, MonstieWash/Assets/Scenes/Game Scenes/Slime/SlimeStartingScene.unity, MonstieWash/ProjectSettings/ProjectSettings.asset
changed ui icons showing incorrect controls in deco and tutorial. also lowered requirements on scan and feeding
=> 654 pax fixes
